### ISSUE TITLE
Use less obviously fake fake email addresses

### ISSUE THREAD

**Issue by rpolley** [SeanDaBlack/KelloggBot#18]
Currently it seems like it would be fairly easy to set up an automated system to detect the fake email addresses this uses, for example the first four I got were all either `example.org` or `example.net` addresses, it might be worth it to throw in some more domains into the mix to throw a wrench in that.

**Comment by pws1453** [comment]
Should be resolved per this commit https://github.com/SeanDaBlack/KelloggBot/commit/0de5def9edabce23c2e983d87817975f6e6e42ef.
