### ISSUE TITLE
Need error handling for lines 134/135

### ISSUE THREAD

**Issue by tabrown2000** [SeanDaBlack/KelloggBot#2]
Lines 134 & 135 occasional throw a "no such element" error, which breaks the main while loop and exits the script. I fixed it by putting a simple try/except block around lines 131-172. Didn't make a pull request cause there's definitely a better solution.

Session info: chrome=96.0.4664.93, macOS Monterey v12.0.1

**Comment by pws1453** [comment]
Same issue here. MacOS Monterey, Chrome Version 96.0.4664.93.

**Comment by tabrown2000** [comment]
More Info: it seems to happen when the page doesn't load properly (i.e. blank white screen). Lines 134/135 are looking for the "topBar" attribute, but if the page doesn't load properly, it errors out. Should probably just break the loop and have the window close and reopen then try again


Also unrelated suggestion, should have a list of more resumes (png, pdf, docx, etc). Upload limit is 9.76MB, should make them as close to that as possible. Could also upload add separate CV file (no file size limit)

**Comment by pws1453** [comment]
My PR should fix this issue, I found that I was running into issue where the code was trying to access URL[4], which doesn't exist.

**Comment by tabrown2000** [comment]
Same lines now running into error but for new reason - "Account already exists" page comes up instead of "account created successfully." Looks like we might run out of fake emails lmao

Surrounding it with a try/except block still handles the error, but it's inefficient. Script should probably be broken into functions to make error handling easier

**Comment by pws1453** [comment]
I created a new issue for this here: https://github.com/SeanDaBlack/KelloggBot/issues/4
Much of the code does need to be restructured.

**Comment by Audibles** [comment]
I just made a PR that should hopefully fix this! was able to run the script for awhile with no issues

**Comment by pws1453** [comment]
Your script looks great! Once it's.... well... not 4am here, and your PR gets accepted, I can merge the work I've been doing on relating to making a couple internal data strctures (read... classes).
