### ISSUE TITLE
Well, they added a reCaptcha -_-

### ISSUE THREAD

**Issue by KathrynElrod** [SeanDaBlack/KelloggBot#23]
`failed to fill out app and submit: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="109:topBar"]"}`

**Comment by Jonodonozym** [comment]
Easy to bypass by clicking the headphones option, downloading the mp3, and putting the mp3 into an speech-to-text converter like this one: https://beecut.com/speech-to-text-online

**Comment by jmrushing** [comment]
@KathrynElrod @Jonodonozym I've never done a pull request on github so I'm not familiar with all the proper best practices, but if either of you are free to do a code review, feel free to steal my work and do your own pull request...
https://gist.github.com/jmrushing/f30f8b1c41111505182e6ceb89ce92bb

It's just a modified req.py based on @Jonodonozym 's previously linked code snippet. You'll have to pip install speech_recognition and pydub, in addition to the usual requirements.txt stuff.

Additionally I've had to modify a few things to make in compatible with linux and my python version 3.8.10 (i.e. swap match case for if statements), but the relevant code for bonking reCaptcha is there and seems to work. Let me know if you have any questions.

**Comment by splpaul** [comment]
Just tested @jmrushing 's updated req.py and it works perfectly on my end, it's defeated all reCaptchas

**Comment by BigweldIndustries** [comment]
Wow, that's incredible! I am going to add that to my fork.

**Comment by BigweldIndustries** [comment]
Alright, my crossplatform fork now contains multithreading, auto install chromedriver, and captcha bypass. may add some form of making it headless

**Comment by pws1453** [comment]
I made a fork of main here such that chrome will run headlessly. I've submitted a PR here https://github.com/SeanDaBlack/KelloggBot/pull/25/files.

**Comment by joeyagreco** [comment]
@jmrushing I [put out a PR ](https://github.com/SeanDaBlack/KelloggBot/pull/26)to implement your changes and cleaned it up a bit... NICE JOB!!

**Comment by MeaningOf42** [comment]
I put out a separate PR I'd been working on before I saw yours also based on @jmrushing 's code.

**Comment by KathrynElrod** [comment]
Closed by #28.
