### ISSUE TITLE
Looks like they messed with Capta Attribute Names

### ISSUE THREAD

**Issue by cribdragg3r** [SeanDaBlack/KelloggBot#31]
```text
FAILED TO FILL OUT APPLICATION AND SUBMIT: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="109:topBar"]"}
  (Session info: chrome=96.0.4664.93)
```

**Comment by bolshoytoster** [comment]
I think this is because it looks for the element before it is loaded. As a temporary solution, you should be able to go to `main.py` line 164:

https://github.com/SeanDaBlack/KelloggBot/blob/66dbcd20fc8e77b2660a4ed1ec3838fb57173dee/main.py#L162-L164

And replace the `10` with a `20`.

**Comment by bolshoytoster** [comment]
I've opened a pull request to resolve this.

**Comment by cribdragg3r** [comment]
Not sure if that was it. I did change the wait time from 10 to 20: Here's a image of the page result:

![image](https://user-images.githubusercontent.com/12776422/145729434-73332ac5-cf8b-45d2-bb47-25a9e253a095.png)

**Comment by cribdragg3r** [comment]
Got it working. I was not on the most recent commit. This issue can be closed and you are a BADASS! Great job.
