### ISSUE TITLE
Email generation - Email already in use. 

### ISSUE THREAD

**Issue by pws1453** [SeanDaBlack/KelloggBot#4]
Emails used to generate accounts are already registered with Kellogg's. Program execution stops at this point.

**Comment by joeyagreco** [comment]
I also ran into this issue
![image](https://user-images.githubusercontent.com/57115019/145650237-8e36d894-1c34-43ca-a7f3-34a2e7319b42.png)

**Comment by pws1453** [comment]
I'm not sure how to resolve this, honestly. Either we could either store a list of used emails (usedemail.conf or the such), or we could make something that this application hooks into that would store a collection of used emails from many users. Once the direction we want to go in is clarified, implementation shouldn't be difficult.

**Comment by pws1453** [comment]
Seems to be resolved enough - closing this for now.
