### ISSUE TITLE
Salary numbers?

### ISSUE THREAD

**Issue by tabrown2000** [SeanDaBlack/KelloggBot#49]
The salary range question on the application is given a random number between 15 and 35, could this be done in a more convincing way? I'm assuming it was written with the thought that "15" means "I expect a salary of $15,000." But then why wouldn't it just be 15000?

It's also asks for "Salary Range," so maybe we should be inputting something like "$25,000-$30,000" or "20k-25k"
Also, I don't think anyone is looking specifically for a salary of "17k" or "31k", I feel like it should be multiples of 5k

**Comment by bolshoytoster** [comment]
@tabrown2000 I can work on this if you want.

**Comment by tabrown2000** [comment]
@bolshoytoster Sure, go for it. I just wanted to make sure I wasn't the only one who thought it was kind of a strange thing to be putting in that entry

**Comment by bolshoytoster** [comment]
@tabrown2000 looking at it now, I'm not sure why it's between 15-35 instead of 15,000-35,000.

There's probably a reason for it so I'll leave that as it is.

**Comment by bolshoytoster** [comment]
I've added a commit to [my fork](https://github.com/bolshoytoster/KelloggBot). I'm not sure if i can open a pr to this repository since it contains some experimental stuff from #25; I could open a pr to that fork if @pws1453 doesn't mind.

**Comment by tabrown2000** [comment]
@bolshoytoster I added your change to my PR (#48) since #25 is still a draft. I still feel like it should be in terms of thousands of dollars, but I'll wait to hear if anyone more people have an opinion on that

**Comment by bolshoytoster** [comment]
@tabrown2000 if you want to change it to thousands you can change the 15, 30, 35 and 5s to thousands i.e.
```python
first = random.randrange(15000, 30000, 5000)
info = f'{first}-{random.randrange(first + 5000, 35000, 5000)}'
```
If you want thousand separators, e.g. 15,000 instead of 15000, you could use the `format(n, ",")` function:
```python
first = random.randrange(15000, 30000, 5000)
info = f'{format(first, ",")}-{format(random.randrange(first + 5000, 35000, 5000), ",")}'
```

**Comment by pws1453** [comment]
> I've added a commit to [my fork](https://github.com/bolshoytoster/KelloggBot). I'm not sure if i can open a pr to this repository since it contains some experimental stuff from #25; I could open a pr to that fork if @pws1453 doesn't mind.

Open a new PR, I'll look through it.
