### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [SeanDaBlack/KelloggBot#8]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by pws1453** [comment]
I don't know how @SeanDaBlack would like this licensed, but it should be considered, and soon.

**Comment by pws1453** [comment]
This is resolved per commit https://github.com/SeanDaBlack/KelloggBot/commit/30cf003a2f8ae682d48e2116bd2134d0a23e60f8.
